[package]
name = "mediator-sys"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
features = []

[dependencies]
async-std = { version = "1.12.0", optional = true }
async-trait =  { version = "0.1.57", optional = true }

[features]
default = []
async = ["async-trait", "async-std"]